### ISSUE TITLE
"Report" is misspelled as "Repot" in various drivers

### ISSUE THREAD

**Issue by brossow** [jtp10181/Hubitat#1]
"Report" is misspelled in some (maybe all?) of the drivers. For example, see line 869 in the ZEN27 driver:

`	return getParam(7, "Send Status Repot to Associations on", 1, 15, associationReportsOptions)`

Thought I should mention it. 😄

**Comment by jtp10181** [comment]
Thanks my normal editor has a spell checker built in but my new one does not, forgot to check everything. I am finding more now and will fix it in the next version.

**Comment by jtp10181** [comment]
Fixed in https://github.com/jtp10181/Hubitat/releases/tag/zooz-v1.3.1
