### ISSUE TITLE
errors in HPM

### ISSUE THREAD

**Issue by tmastersmart** [jtp10181/Hubitat#11]
Error downloading https://raw.githubusercontent.com/jtp10181/Hubitat/main/Drivers/zooz/packageManifest.json

**Comment by tmastersmart** [comment]
Bad manifest for Zooz Switches Advanced Drivers. java.lang.NullPointerException: Cannot get property 'betaLocation' on null object Please notify the package developer.

**Comment by jtp10181** [comment]
I moved that file a while ago, you need to Un-Match in HPM and the run the Matchup again so it finds the new packageManifest file.
