### ISSUE TITLE
Add deviceModel to the data section of the ZSE44

### ISSUE THREAD

**Issue by waterboysh** [jtp10181/Hubitat#21]
The ZSE44 is missing deviceModel from the data section like you have for other devices.

**Comment by jtp10181** [comment]
Thanks for adding this on here! Keeps me organized.

**Comment by jtp10181** [comment]
Resolved here: https://github.com/jtp10181/Hubitat/commit/ec9d04aa2202cb09c74802dbf1d6304e2aa29440
