### ISSUE TITLE
Zen30 firmware 4.10

### ISSUE THREAD

**Issue by SurgeHawk** [jtp10181/Hubitat#25]
Firmware 4.10 added some parameters that aren't defined in the driver currently. 

Is there anyway to add those parameters?

VER. 800LR (released 11/2023)

Hardware:

    800 Series Z-Wave chip

Firmware: 4.10

    Long Range Ready
    Separated ramp rate settings into 4 new parameters: ramp rate ON physical (13), ramp rate OFF physical (31), ramp rate ON Z-Wave (32), and ramp rate OFF Z-Wave (33). [See all settings here.](https://www.support.getzooz.com/kb/article/468-zen30-double-switch-advanced-settings/)
    Adjust Double Tap (parameter 17) and Single Tap (parameter 18) behavior to match ZEN72 and ZEN77 dimmers.

**Comment by jtp10181** [comment]
I have a fix posted on a separate link temporarily, as a Beta version while I work on overhauling all 3 switch drivers.
https://community.hubitat.com/t/driver-zooz-zen-switches-advanced-and-dimmers/58649/448?u=jtp10181

**Comment by jtp10181** [comment]
I am going to keep this as an open issue until I post it as a final version, in case anyone else finds this in here it will give them the info they need.

**Comment by jtp10181** [comment]
This is pushed to main branch now: https://github.com/jtp10181/Hubitat/commit/6e9c599fa944df355b3f99d3653e99921c2d2a4f
