### ISSUE TITLE
HPM error downloading either Zooz ZSE40 4-in-1 Multisensor or Zooz ZEN Plugs Universal

### ISSUE THREAD

**Issue by CurtisZM** [jtp10181/Hubitat#29]
geting an error when downloading either Zooz ZSE40 4-in-1 Multisensor or Zooz ZEN Plugs Universal via HPM

Failed download of file
An error occurred downloading https://jtp10181.gateway.scarf.sh/zooz-zen-plugs-v1.2.2.groovy

Failed download of file
An error occurred downloading https://jtp10181.gateway.scarf.sh/zooz-zse40-v1.2.0.groovy

**Comment by jtp10181** [comment]
Could not reproduce, working for myself and everyone else that I am aware of.
