### ISSUE TITLE
Leviton DZ6HD fails query

### ISSUE THREAD

**Issue by rmdonnelly1** [jtp10181/Hubitat#32]
My Leviton DZ6HD dimmers do not respond to the initial discovery query (see attached):
![Screenshot 2024-07-08 at 1 22 15 PM](https://github.com/jtp10181/Hubitat/assets/36243218/02e39051-eb30-4c0a-a2e8-c52a44a727fa)

firmwareVersion: 1.22
hardwareVersion: 255
configVals: [:]

**Comment by jtp10181** [comment]
Yeah those are the older models, the device needs to support the Configuration command class v3 or higher to have the commands required to query for the parameter info. If you have debug logging on it should list the actual version number returned in the logs.
