### ISSUE TITLE
ZEN71 and ZEN72 Pending changes, even after upgrade to firmware 10

### ISSUE THREAD

**Issue by jchonig** [jtp10181/Hubitat#9]
I configured a ZEN71 and ZEN72 for momentary 3-way (for use with ZAC99) and notice both have pending changes.

I upgraded the ZEN71 from firmware 1.03 to 10 and still have the issue.  A log when I press *Save Preferences* shows this:

```dev:3662021-12-30 12:10:05.006 debugEntryway: Stairs: paddleControl (#1) = 0
dev:3662021-12-30 12:10:04.385 debugEntryway: Stairs: Changing associationReports (#7) from null to 15
dev:3662021-12-30 12:10:03.864 debugEntryway: Stairs: executeConfigureCmds...
dev:3662021-12-30 12:10:02.899 warnDescription logging is: true
dev:3662021-12-30 12:10:02.896 warnDebug logging is: true
dev:3662021-12-30 12:10:02.881 infoupdated...
```

```Hubitat Elevation® Platform Version
2.3.0.121
Hardware Version
Rev C-7
```

Package manager claims I'm up to date:

```Zooz Switches Advanced Drivers Documentation | Community Thread | Donate
Child Central Scene Switch v1.0.0 (driver)
Zooz ZEN Dimmer Advanced v1.5.0 (driver)
Zooz ZEN Switch Advanced v1.5.0 (driver)
Zooz ZEN30 Double Switch v1.4.4 (driver)
```

A log from the ZEN72 which is running firmware 1.03

```dev:1692021-12-30 12:17:46.019 debugKitchen: Table light: paddleControl (#1) = 0
dev:1692021-12-30 12:17:45.534 debugKitchen: Table light: Changing associationReports (#7) from null to 15
dev:1692021-12-30 12:17:44.699 debugKitchen: Table light: executeConfigureCmds...
dev:1692021-12-30 12:17:43.641 warnDescription logging is: true
dev:1692021-12-30 12:17:43.638 warnDebug logging is: true
dev:1692021-12-30 12:17:43.635 infoupdated...
```

Any more debugging info I can provide?

Thanks.

Jeff

**Comment by jtp10181** [comment]
Can you edit the driver code and uncomment the log.trace at the very bottom. Also enable the debugging on the device. Then try again to confirm my suspicion. Post a screenshot of the log entry if you can, that is easier to read than a text paste. There should be some trace stuff that comes back after it tries to change the parameter. I suspect Zooz did not include that parameter in those two devices for some reason. Those are the only two I do not have myself to test on.

**Comment by jchonig** [comment]
Here is the log after that change and hitting Save Preference and then a Configure.  What's confusing is that I don't see the prior messages in this log?

<img width="1319" alt="Screen Shot 2021-12-31 at 6 59 48 PM" src="https://user-images.githubusercontent.com/4303886/147841363-1cae081d-7c31-4a13-8197-8f0c47f61551.png">

I like these because the style matches the ZEN32 scene controllers I have.

**Comment by jtp10181** [comment]
You must have forgotten to turn on debug logging again, but no worries I can see that the value being returned is paramNum 1, which means that the one it is trying to set, is not valid for that device.

It is not actually hurting anything besides being annoying. If you want to fix it for now you can edit the code to remove that parameter from the 71 and 72. On the dimmer driver this is around line 424, or 357 for the switch. I will just add the 'changes' section as shown below to my next update to fix it.

```
	associationReports: [ num: 7,
		title: "Send Status Report to Associations on", 
		size: 1, defaultVal: 15, 
		options: [ 0:"None", 1:"Physical Tap On ZEN Only", 2:"Physical Tap On Connected 3-Way Switch Only", 3:"Physical Tap On ZEN / 3-Way Switch",
			4:"Z-Wave Command From Hub", 5:"Physical Tap On ZEN / Z-Wave Command", 6:"Physical Tap On 3-Way Switch / Z-Wave Command",
			7:"Physical Tap On ZEN / 3-Way Switch / Z-Wave Command", 8:"Timer Only", 9:"Physical Tap On ZEN / Timer",
			10:"Physical Tap On 3-Way Switch / Timer", 11:"Physical Tap On ZEN / 3-Way Switch / Timer", 12:"Z-Wave Command From Hub / Timer",
			13:"Physical Tap On ZEN / Z-Wave Command / Timer", 14:"Physical Tap On ZEN / 3-Way Switch / Z-Wave Command / Timer",
			15:"All Of The Above" 
		],
		changes: [71:[num:null], 72:[num:null]]
	],
```

**Comment by jchonig** [comment]
You are right, I didn't have debug logging on.  I glanced and had Descriptive Text logging on and mis-read it.

Making those changes gets past that parameter.  Now we are back to the core issue I was having, setting the 3-way switch type on the ZEN71.  It works on the ZEN72, but on the ZEN71 it does not get set and I have 1 change pending.

<img width="1329" alt="Screen Shot 2022-01-01 at 4 14 59 PM" src="https://user-images.githubusercontent.com/4303886/147860354-ee062eff-079f-4914-9fba-f0b09dee71d5.png">

Looking at the [docs](https://www.support.getzooz.com/kb/article/535-zen71-on-off-switch-700-advanced-settings/), this switch only allows values of #12 of 0 (on/off) or 1 (momentary).

Using the menu item for *Toggle On/Off with 2x/3x* which sets it to 1, results in a proper sync.  However the ZAC99 now does nothing.  I'll have to reach out to to Zooz about that.

The [ZEN72 docs ](https://www.support.getzooz.com/kb/article/538-zen72-dimmer-switch-700-advanced-settings/) indicate that it supports the full set of values for parameter 19.

Would it be useful to have a ZEN71 and ZEN72, I could send you a pair.

Thanks.

Jeff

**Comment by jtp10181** [comment]
Setting it to 1 should do the trick and allow the momentary to work, so if that's not working it could be a firmware issue. As far as the parameter options... this one is a pain because half have 2 options and half have 4, so the make the code less confusing I am going to split it into two sections. On your switch driver if you want to test, around line 339, the threeWaySwitchType is changed and threeWaySwitchType2 is added.

```
	threeWaySwitchType: [num: null, // (12)
		title: "3-Way Switch Type",
		size: 1, defaultVal: 0, 
		options: [0:"Toggle On/Off Switch", 1:"Momentary Switch"],
		changes: [21:[num: 12],23:[num: 12],71:[num: 12]]
	],
	threeWaySwitchType2: [num: null, // (19)
		title: "3-Way Switch Type",
		size: 1, defaultVal: 0, 
		options: [0:"Toggle On/Off Switch", 1:"Toggle On/Off with 2x/3x Shortcuts", 2:"Momentary Switch", 3:"Momentary with 2x/Hold Shortcuts"],
		changes: [22:[num: 19],24:[num: 19],72:[num: 19]]
	],
```

**Comment by jchonig** [comment]
That seems to do the right thing as far as setting the parameter goes.  The switch is not responding to the traveller input at all, I'm discussing that with Zooz support.

Thanks.

Jeff

**Comment by jtp10181** [comment]
Great, I will get an update out with those fixes soon.

**Comment by jtp10181** [comment]
This was fixed with commit https://github.com/jtp10181/Hubitat/commit/e0d2c6c104850720972c9c443ca861c1387d33f0
